import platform

print("\x1b[32mScyndi's Creative Interpreter\x1b[33m\tBuilder script for the API Header Generator\x1b[0m\n(c) Jeroen P. Broks\n")
def Doing(a,b): print("\x1b[93m%s: \x1b[96m%s\x1b[0m"%(a,b))
Doing("Platform",platform.system())
print("/n/n")



# Base Functions
Files = []
Libs = []

def Add(cat,files):
    for f in files: 
        Doing(cat,f)
        Files.append(f)

def AddLib(cat,files):
    for f in files: 
        Doing("Lib "+cat,f)
        Files.append(f)
Add("Units",[        
    "../../../Libs/Units/Source/SlyvDir.cpp",
    "../../../Libs/Units/Source/SlyvDirry.cpp",
    "../../../Libs/Units/Source/SlyvQCol.cpp",
    "../../../Libs/Units/Source/SlyvSTOI.cpp",
    "../../../Libs/Units/Source/SlyvStream.cpp",
    "../../../Libs/Units/Source/SlyvString.cpp",
    "../../../Libs/Units/Source/SlyvTime.cpp",
    "../../../Libs/Units/Source/SlyvVolumes.cpp"])
Add("App",["APIHeader.cpp"])
Program("apiheader_%s"%platform.system().lower(),Files,CPPPATH="../../../Libs/Units/Headers")