#pragma once
#include <string>

// This code is generated by QVersion! It's best NOT to manutally alter it!

namespace Scyndi_CI {
	class QVersionClass {
	public:
		unsigned int giant{0}, major{0}, minor{0}; 
		std::string dt{"00000000000000"};
		std::string Status{"Stable"};
		inline std::string Version(bool full=true) {
			std::string ret{ std::to_string(giant)+"."+std::to_string(major)+"."+std::to_string(minor) };
			if (full) ret+="."+dt;
			if (Status!="Stable") ret += " (" + Status + ")";
			return ret;
		}
		inline QVersionClass(){} // Fuck you!
		inline QVersionClass(unsigned int _giant,unsigned int _major,unsigned int _minor,std::string _dt="00000000000000",std::string _status="Stable") {
			giant=_giant; major=_major; minor=_minor; dt=_dt; Status=_status;
		}
	};

	static QVersionClass QVersion{1,7,8,"20250430165052","Alpha"};

} // namespace Scyndi_CI
